Repository bots-garden/capsule, pull requests merged in 2022-09, with the labels that each got.

#118 ✨ feature add KEYS command to the Redis host functions
  capsule-launcher/hostfunctions/redis.go
  capsule-launcher/services/wasmrt/wasmrt.go
  capsulemodule/hostfunctions/redis.go
  wasm_modules/capsule-redis-keys/.gitignore
  wasm_modules/capsule-redis-keys/README.md
  wasm_modules/capsule-redis-keys/build.sh
  wasm_modules/capsule-redis-keys/go.mod
  wasm_modules/capsule-redis-keys/go.sum
  wasm_modules/capsule-redis-keys/hello.go
  wasm_modules/capsule-redis-keys/run-cli-test.sh
Labels: 0.1.8

#116 deps: updates wazero to 1.0.0-pre.1
  capsule-launcher/go.mod
  capsule-launcher/go.sum
  capsule-launcher/services/wasmrt/wasmrt.go
Labels: 0.1.8, dependencies

#167 add mqtt support
  README.md
  capsule-launcher/go.mod
  capsule-launcher/go.sum
  capsule-launcher/hostfunctions/mqtt.go
  capsule-launcher/main.go
  capsule-launcher/services/mqtt/mqtt.go
  capsule-launcher/services/wasmrt/wasmrt.go
  capsule-launcher/services/wasmrt/wasmrunner.go
  capsulemodule/hostfunctions/handlemqtt.go
  capsulemodule/hostfunctions/mqtt.go
  mqtt/clients/node-js-client/package.json
  mqtt/clients/node-js-client/publisher.js
  mqtt/clients/node-js-client/subscriber.js
  mqtt/config/mosquitto.conf
  mqtt/docker-compose.yml
  mqttconn/go.mod
  mqttconn/go.sum
  mqttconn/mqtt.go
  wasm_modules/capsule-mqtt-publisher/build.sh
  wasm_modules/capsule-mqtt-publisher/go.mod
  wasm_modules/capsule-mqtt-publisher/go.sum
  wasm_modules/capsule-mqtt-publisher/hello.go
  wasm_modules/capsule-mqtt-publisher/refresh_package.sh
  wasm_modules/capsule-mqtt-publisher/run.sh
  wasm_modules/capsule-mqtt-subscriber/build.sh
  wasm_modules/capsule-mqtt-subscriber/go.mod
  wasm_modules/capsule-mqtt-subscriber/hello.go
  wasm_modules/capsule-mqtt-subscriber/refresh_package.sh
  wasm_modules/capsule-mqtt-subscriber/run.sh
Labels: enhancement, host function, host, wasm module, capsule launcher (capsule), review in progress, v0.2.5
