Repository bots-garden/capsule, pull requests merged in 2022-10, with the labels that each got.

#190 📝 update doc use mkdock
  DOCS.md
  README.md
  docs/capsule-faas.md
  docs/dev-guide.md
  docs/host-functions.md
  docs/index.md
  docs/install.md
  docs/references.md
  docs/tooling.md
  git.sh
  mkdocs.yml
Labels: documentation, v0.2.9

#197 fix instructions for macOS
  docs/getting-started.md
  docs/install.md
Labels: documentation

#188 ✨ feature wasm module hot reloading
  capsule-launcher/services/http/httpfiber.go
  capsule-launcher/services/http/requestfiber.go
  capsule-launcher/services/wasmrt/wasmfile.go
  capsule-launcher/services/wasmrt/wasmrt.go
  capsule-launcher/services/wasmrt/wasmrunner.go
  wasm_modules/capsule-hello-post/hello.go
  wasm_modules/hot-reload/hello-one/.gitignore
  wasm_modules/hot-reload/hello-one/build.sh
  wasm_modules/hot-reload/hello-one/go.mod
  wasm_modules/hot-reload/hello-one/go.sum
  wasm_modules/hot-reload/hello-one/hello.go
  wasm_modules/hot-reload/hello-one/refresh_package.sh
  wasm_modules/hot-reload/hello-two/.gitignore
  wasm_modules/hot-reload/hello-two/build.sh
  wasm_modules/hot-reload/hello-two/go.mod
  wasm_modules/hot-reload/hello-two/go.sum
  wasm_modules/hot-reload/hello-two/hello.go
  wasm_modules/hot-reload/hello-two/refresh_package.sh
  wasm_modules/hot-reload/query.sh
  wasm_modules/hot-reload/re-load-module-one.sh
  wasm_modules/hot-reload/re-load-module-two.sh
  wasm_modules/hot-reload/serve-wasm-files.sh
  wasm_modules/hot-reload/start.sh
  wasm_modules/hot-reload/tmp/.gitkeep.go
Labels: enhancement, 🚧 in progress, wasm module, capsule launcher (capsule), v0.2.9
